### ISSUE TITLE
"While True" Error

### ISSUE THREAD

**Issue by adamsr1** [adafruit/Adafruit_CircuitPython_NeoPixel#125]
When putting this code into python on a 4b, I get an error when I hit run.  It says "True is not defined" in the following code
```py
while True:
    pixels.fill((255, 0, 0, 0))
    pixels.show()
    time.sleep(1)

    pixels.fill((0, 255, 0, 0))
    pixels.show()
    time.sleep(1)

    pixels.fill((0, 0, 255, 0))
    pixels.show()
    time.sleep(1)

    rainbow_cycle(0.001)
```

How do I correct this?

**Comment by caternuson** [comment]
Please post the full text of the error message output. It is likely multiple lines of text. Please post all of them.

**Comment by adamsr1** [comment]
Fixed the "True" error but I am getting this now and I don't understand it. Please help.

Can't open /dev/mem: Permission denied
Traceback (most recent call last):
  File "/home/pi/Desktop/light ring.py", line 37, in <module>
    pixels.fill((255,0,0,0))
  File "/usr/local/lib/python3.7/dist-packages/adafruit_pixelbuf.py", line 216, in fill
    self.show()
  File "/usr/local/lib/python3.7/dist-packages/adafruit_pixelbuf.py", line 204, in show
    return self._transmit(self._post_brightness_buffer)
  File "/usr/local/lib/python3.7/dist-packages/neopixel.py", line 180, in _transmit
    neopixel_write(self.pin, buffer)
  File "/usr/local/lib/python3.7/dist-packages/neopixel_write.py", line 38, in neopixel_write
    return _neopixel.neopixel_write(gpio, buf)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/bcm283x/neopixel.py", line 79, in neopixel_write
    "NeoPixel support requires running with sudo, please try again!"
RuntimeError: NeoPixel support requires running with sudo, please try again!

**Comment by ladyada** [comment]
Hi there, for help with running Python, please post to user forums. For example, if its a Raspberry Pi - there's forums at https://forums.raspberrypi.com/ - if its a product purchased from adafruit, there's forums.adafruit.com/ - etc!
