### ISSUE TITLE
Support NeoPixel on Rock Pi S

### ISSUE THREAD

**Issue by ab-tools** [adafruit/Adafruit_CircuitPython_NeoPixel#131]
When trying to use this NeoPixel library on a [Rock Pi S](https://wiki.radxa.com/RockpiS) I've get following error message:
```
Traceback (most recent call last):
  File "./led-test.py", line 8, in <module>
    import neopixel
  File "/usr/local/lib/python3.8/dist-packages/neopixel.py", line 18, in <module>
    from neopixel_write import neopixel_write
  File "/usr/local/lib/python3.8/dist-packages/neopixel_write.py", line 33, in <module>
    raise NotImplementedError("Board not supported")
NotImplementedError: Board not supported
```

Is there a chance to add support for Rock Pi boards for this NeoPixel library as well?

Thanks in advance
Andreas

**Comment by ladyada** [comment]
nice work! will close as resolved
