### ISSUE TITLE
Raspberry pi 5 Cannot determine SOC peripheral base address

### ISSUE THREAD

**Issue by davidpazo** [adafruit/Adafruit_CircuitPython_NeoPixel#164]
Hi,
I am trying to use the NeoPixel library with my Raspberry Pi 5, but I am encountering the following error:

```
Traceback (most recent call last):
  File "/home/usuario/program/driver/program.py", line 14, in <module>
    leds = neopixel.NeoPixel(board.D21, 200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/neopixel.py", line 141, in __init__
    self.pin = digitalio.DigitalInOut(pin)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/digitalio.py", line 193, in __init__
    self.direction = Direction.INPUT
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/digitalio.py", line 223, in direction
    self._pin.init(mode=Pin.IN)
  File "/usr/local/lib/python3.11/dist-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 40, in init
    GPIO.setup(self.id, GPIO.IN)
RuntimeError: Cannot determine SOC peripheral base address
```

I read that the Raspberry Pi 5 has some incompatibilities with the GPIOs. Does anyone have a solution for this? Or should I wait for an update?

Thank you in advance!

**Comment by offbrandmark** [comment]
Yeah the Pi 5 has some hardware changes that makes it have incompatibilities. Check out [this issue](https://github.com/jgarff/rpi_ws281x/issues/528) from the rpi_ws281x library, this includes their development of raspberry pi 5 using the LEDs. No release from them but some users have made some fixes.

Hope this helps!
