### ISSUE TITLE
Error when setting pixel value to a list value (circuitpython 4.0.0beta)

### ISSUE THREAD

**Issue by cpforbes** [adafruit/Adafruit_CircuitPython_NeoPixel#39]
When setting a pixel with a list for the value:
```
>>> import board
>>> import neopixel
>>> NUMPIXELS = 16
>>> neopixels = neopixel.NeoPixel(board.D4, NUMPIXELS, brightness=0.2, auto_write=False)
>>> neopixels[1] = [0,0,0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "neopixel.py", line 169, in __setitem__
  File "neopixel.py", line 148, in _set_item
TypeError: unsupported types for __add__: 'list', 'tuple'
```

This appears to be from the tuple addition used here:
https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/blob/6e35cd2b40575a20e2904b096508325cef4a71d3/neopixel.py#L148

**Comment by tannewt** [comment]
@cpforbes Want to try fixing it? I can help if you have any questions.

**Comment by cpforbes** [comment]
@tannewt Sure. Will work on a PR.
