### ISSUE TITLE
The example from the docs gives an error

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_NeoPixel#4]
`from adafruit_circuitplayground.express import circuit`

`circuit.pixels[0] = 0x000300`
`circuit.pixels[9] = 0x030000`

`while True:`
`    pass`

The error is: 
`main.py output:`
`Traceback (most recent call last):`
`  File "main.py", line 3, in <module>`
`  File "neopixel.py", line 25, in __setitem__`
`TypeError: 'int' object is not subscriptable`

**Comment by kattni** [comment]
The previous version of neopixel.mpy was still present on the CPX. It was causing the error.
